USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[DIRECCION]    Script Date: 7/1/2026 20:30:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIRECCION](
	[id_direccion] [int] IDENTITY(1,1) NOT NULL,
	[provincia] [nvarchar](60) NOT NULL,
	[canton] [nvarchar](60) NOT NULL,
	[distrito] [nvarchar](60) NOT NULL,
	[barrio] [nvarchar](60) NULL,
	[senas_exactas] [nvarchar](300) NOT NULL,
 CONSTRAINT [PK_DIRECCION] PRIMARY KEY CLUSTERED 
(
	[id_direccion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[TIPO_ACTIVIDAD]    Script Date: 7/1/2026 20:30:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIPO_ACTIVIDAD](
	[id_tipo_actividad] [int] IDENTITY(1,1) NOT NULL,
	[nombre_tipo_actividad] [nvarchar](80) NOT NULL,
 CONSTRAINT [PK_TIPO_ACTIVIDAD] PRIMARY KEY CLUSTERED 
(
	[id_tipo_actividad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_TIPO_ACTIVIDAD_NOMBRE] UNIQUE NONCLUSTERED 
(
	[nombre_tipo_actividad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[EMPRESA_RECREATIVA]    Script Date: 7/1/2026 20:30:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPRESA_RECREATIVA](
	[cedula_juridica_empresa] [varchar](25) NOT NULL,
	[nombre_empresa] [nvarchar](120) NOT NULL,
	[correo_electronico] [varchar](254) NOT NULL,
	[nombre_contacto] [nvarchar](120) NOT NULL,
	[descripcion_actividad] [nvarchar](600) NOT NULL,
	[servicios_que_brinda] [nvarchar](600) NULL,
	[precio] [decimal](12, 2) NOT NULL,
	[id_direccion] [int] NOT NULL,
	[id_tipo_actividad] [int] NULL,
 CONSTRAINT [PK_EMPRESA_RECREATIVA] PRIMARY KEY CLUSTERED 
(
	[cedula_juridica_empresa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_EMPRESA_RECREATIVA_CORREO] UNIQUE NONCLUSTERED 
(
	[correo_electronico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESA_RECREATIVA_DIRECCION] FOREIGN KEY([id_direccion])
REFERENCES [dbo].[DIRECCION] ([id_direccion])
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA] CHECK CONSTRAINT [FK_EMPRESA_RECREATIVA_DIRECCION]
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESA_RECREATIVA_TIPO_ACTIVIDAD] FOREIGN KEY([id_tipo_actividad])
REFERENCES [dbo].[TIPO_ACTIVIDAD] ([id_tipo_actividad])
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA] CHECK CONSTRAINT [FK_EMPRESA_RECREATIVA_TIPO_ACTIVIDAD]
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA]  WITH CHECK ADD  CONSTRAINT [CK_EMPRESA_RECREATIVA_PRECIO] CHECK  (([precio]>=(0)))
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA] CHECK CONSTRAINT [CK_EMPRESA_RECREATIVA_PRECIO]
GO

USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[EMPRESA_RECREATIVA_TELEFONO]    Script Date: 7/1/2026 20:31:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPRESA_RECREATIVA_TELEFONO](
	[cedula_juridica_empresa] [varchar](25) NOT NULL,
	[codigo_pais] [varchar](6) NOT NULL,
	[numero] [varchar](20) NOT NULL,
 CONSTRAINT [PK_EMPRESA_RECREATIVA_TELEFONO] PRIMARY KEY CLUSTERED 
(
	[cedula_juridica_empresa] ASC,
	[numero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA_TELEFONO]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESA_RECREATIVA_TELEFONO_EMPRESA] FOREIGN KEY([cedula_juridica_empresa])
REFERENCES [dbo].[EMPRESA_RECREATIVA] ([cedula_juridica_empresa])
GO

ALTER TABLE [dbo].[EMPRESA_RECREATIVA_TELEFONO] CHECK CONSTRAINT [FK_EMPRESA_RECREATIVA_TELEFONO_EMPRESA]
GO

USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[SERVICIO]    Script Date: 7/1/2026 20:31:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SERVICIO](
	[id_servicio] [int] IDENTITY(1,1) NOT NULL,
	[nombre_servicio] [nvarchar](80) NOT NULL,
 CONSTRAINT [PK_SERVICIO] PRIMARY KEY CLUSTERED 
(
	[id_servicio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_SERVICIO_NOMBRE] UNIQUE NONCLUSTERED 
(
	[nombre_servicio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[COMODIDAD]    Script Date: 7/1/2026 20:32:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMODIDAD](
	[id_comodidad] [int] IDENTITY(1,1) NOT NULL,
	[nombre_comodidad] [nvarchar](80) NOT NULL,
 CONSTRAINT [PK_COMODIDAD] PRIMARY KEY CLUSTERED 
(
	[id_comodidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_COMODIDAD_NOMBRE] UNIQUE NONCLUSTERED 
(
	[nombre_comodidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[HOSPEDAJE]    Script Date: 7/1/2026 20:31:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HOSPEDAJE](
	[cedula_juridica] [varchar](25) NOT NULL,
	[nombre] [nvarchar](120) NOT NULL,
	[tipo_hospedaje] [nvarchar](40) NOT NULL,
	[correo_electronico] [varchar](254) NOT NULL,
	[url_sitio_web] [varchar](500) NULL,
	[referencia_gps] [varchar](120) NULL,
	[id_direccion] [int] NOT NULL,
 CONSTRAINT [PK_HOSPEDAJE] PRIMARY KEY CLUSTERED 
(
	[cedula_juridica] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_HOSPEDAJE_CORREO] UNIQUE NONCLUSTERED 
(
	[correo_electronico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HOSPEDAJE]  WITH CHECK ADD  CONSTRAINT [FK_HOSPEDAJE_DIRECCION] FOREIGN KEY([id_direccion])
REFERENCES [dbo].[DIRECCION] ([id_direccion])
GO

ALTER TABLE [dbo].[HOSPEDAJE] CHECK CONSTRAINT [FK_HOSPEDAJE_DIRECCION]
GO

ALTER TABLE [dbo].[HOSPEDAJE]  WITH CHECK ADD  CONSTRAINT [CK_HOSPEDAJE_TIPO] CHECK  (([tipo_hospedaje]='Cabaña' OR [tipo_hospedaje]='Departamento' OR [tipo_hospedaje]='Casa' OR [tipo_hospedaje]='Hostal' OR [tipo_hospedaje]='Hotel'))
GO

ALTER TABLE [dbo].[HOSPEDAJE] CHECK CONSTRAINT [CK_HOSPEDAJE_TIPO]
GO


USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[HOSPEDAJE_REDSOCIAL]    Script Date: 7/1/2026 20:31:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HOSPEDAJE_REDSOCIAL](
	[cedula_juridica_hospedaje] [varchar](25) NOT NULL,
	[plataforma] [nvarchar](30) NOT NULL,
	[url_perfil] [varchar](500) NOT NULL,
 CONSTRAINT [PK_HOSPEDAJE_REDSOCIAL] PRIMARY KEY CLUSTERED 
(
	[cedula_juridica_hospedaje] ASC,
	[plataforma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HOSPEDAJE_REDSOCIAL]  WITH CHECK ADD  CONSTRAINT [FK_HOSPEDAJE_REDSOCIAL_HOSPEDAJE] FOREIGN KEY([cedula_juridica_hospedaje])
REFERENCES [dbo].[HOSPEDAJE] ([cedula_juridica])
GO

ALTER TABLE [dbo].[HOSPEDAJE_REDSOCIAL] CHECK CONSTRAINT [FK_HOSPEDAJE_REDSOCIAL_HOSPEDAJE]
GO

USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[HOSPEDAJE_TELEFONO]    Script Date: 7/1/2026 20:32:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HOSPEDAJE_TELEFONO](
	[cedula_juridica_hospedaje] [varchar](25) NOT NULL,
	[codigo_pais] [varchar](6) NOT NULL,
	[numero] [varchar](20) NOT NULL,
 CONSTRAINT [PK_HOSPEDAJE_TELEFONO] PRIMARY KEY CLUSTERED 
(
	[cedula_juridica_hospedaje] ASC,
	[numero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HOSPEDAJE_TELEFONO]  WITH CHECK ADD  CONSTRAINT [FK_HOSPEDAJE_TELEFONO_HOSPEDAJE] FOREIGN KEY([cedula_juridica_hospedaje])
REFERENCES [dbo].[HOSPEDAJE] ([cedula_juridica])
GO

ALTER TABLE [dbo].[HOSPEDAJE_TELEFONO] CHECK CONSTRAINT [FK_HOSPEDAJE_TELEFONO_HOSPEDAJE]
GO

USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[TIPO_HABITACION]    Script Date: 7/1/2026 20:32:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIPO_HABITACION](
	[id_tipo_habitacion] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](80) NOT NULL,
	[descripcion] [nvarchar](400) NOT NULL,
	[tipo_cama] [nvarchar](20) NOT NULL,
	[precio] [decimal](12, 2) NOT NULL,
 CONSTRAINT [PK_TIPO_HABITACION] PRIMARY KEY CLUSTERED 
(
	[id_tipo_habitacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TIPO_HABITACION]  WITH CHECK ADD  CONSTRAINT [CK_TIPO_HABITACION_PRECIO] CHECK  (([precio]>=(0)))
GO

ALTER TABLE [dbo].[TIPO_HABITACION] CHECK CONSTRAINT [CK_TIPO_HABITACION_PRECIO]
GO




USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[FOTO_TIPOHABITACION]    Script Date: 7/1/2026 20:32:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOTO_TIPOHABITACION](
	[id_foto] [int] IDENTITY(1,1) NOT NULL,
	[url_foto] [varchar](500) NOT NULL,
	[id_tipo_habitacion] [int] NOT NULL,
 CONSTRAINT [PK_FOTO_TIPOHABITACION] PRIMARY KEY CLUSTERED 
(
	[id_foto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_FOTO_TIPOHABITACION_URL] UNIQUE NONCLUSTERED 
(
	[url_foto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOTO_TIPOHABITACION]  WITH CHECK ADD  CONSTRAINT [FK_FOTO_TIPOHABITACION_TIPO] FOREIGN KEY([id_tipo_habitacion])
REFERENCES [dbo].[TIPO_HABITACION] ([id_tipo_habitacion])
GO

ALTER TABLE [dbo].[FOTO_TIPOHABITACION] CHECK CONSTRAINT [FK_FOTO_TIPOHABITACION_TIPO]
GO

USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[HABITACION]    Script Date: 7/1/2026 20:33:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HABITACION](
	[id_habitacion] [int] IDENTITY(1,1) NOT NULL,
	[numero] [nvarchar](20) NOT NULL,
	[estado] [nvarchar](10) NOT NULL,
	[url_foto] [varchar](500) NULL,
	[cedula_juridica_hospedaje] [varchar](25) NOT NULL,
	[id_tipo_habitacion] [int] NOT NULL,
 CONSTRAINT [PK_HABITACION] PRIMARY KEY CLUSTERED 
(
	[id_habitacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_HABITACION_NUMERO_POR_HOSPEDAJE] UNIQUE NONCLUSTERED 
(
	[cedula_juridica_hospedaje] ASC,
	[numero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HABITACION]  WITH CHECK ADD  CONSTRAINT [FK_HABITACION_HOSPEDAJE] FOREIGN KEY([cedula_juridica_hospedaje])
REFERENCES [dbo].[HOSPEDAJE] ([cedula_juridica])
GO

ALTER TABLE [dbo].[HABITACION] CHECK CONSTRAINT [FK_HABITACION_HOSPEDAJE]
GO

ALTER TABLE [dbo].[HABITACION]  WITH CHECK ADD  CONSTRAINT [FK_HABITACION_TIPO] FOREIGN KEY([id_tipo_habitacion])
REFERENCES [dbo].[TIPO_HABITACION] ([id_tipo_habitacion])
GO

ALTER TABLE [dbo].[HABITACION] CHECK CONSTRAINT [FK_HABITACION_TIPO]
GO

ALTER TABLE [dbo].[HABITACION]  WITH CHECK ADD  CONSTRAINT [CK_HABITACION_ESTADO] CHECK  (([estado]='Inactivo' OR [estado]='Activo'))
GO

ALTER TABLE [dbo].[HABITACION] CHECK CONSTRAINT [CK_HABITACION_ESTADO]
GO


USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[CLIENTE]    Script Date: 7/1/2026 20:33:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTE](
	[identificacion] [varchar](25) NOT NULL,
	[tipo_identificacion] [nvarchar](30) NOT NULL,
	[apellido1] [nvarchar](80) NOT NULL,
	[apellido2] [nvarchar](80) NULL,
	[fecha_nacimiento] [date] NOT NULL,
	[pais_residencia] [nvarchar](80) NOT NULL,
	[correo_electronico] [varchar](254) NOT NULL,
	[id_direccion] [int] NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[identificacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_CLIENTE_CORREO] UNIQUE NONCLUSTERED 
(
	[correo_electronico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_DIRECCION] FOREIGN KEY([id_direccion])
REFERENCES [dbo].[DIRECCION] ([id_direccion])
GO

ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_DIRECCION]
GO


USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[CLIENTE_TELEFONO]    Script Date: 7/1/2026 20:33:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTE_TELEFONO](
	[identificacion_cliente] [varchar](25) NOT NULL,
	[codigo_pais] [varchar](6) NOT NULL,
	[numero] [varchar](20) NOT NULL,
 CONSTRAINT [PK_CLIENTE_TELEFONO] PRIMARY KEY CLUSTERED 
(
	[identificacion_cliente] ASC,
	[numero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CLIENTE_TELEFONO]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_TELEFONO_CLIENTE] FOREIGN KEY([identificacion_cliente])
REFERENCES [dbo].[CLIENTE] ([identificacion])
GO

ALTER TABLE [dbo].[CLIENTE_TELEFONO] CHECK CONSTRAINT [FK_CLIENTE_TELEFONO_CLIENTE]
GO


USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[RESERVACION]    Script Date: 7/1/2026 20:33:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RESERVACION](
	[id_reservacion] [int] IDENTITY(1,1) NOT NULL,
	[fecha_hora_ingreso] [datetime2](0) NOT NULL,
	[fecha_salida] [datetime2](0) NOT NULL,
	[cantidad_personas] [int] NOT NULL,
	[posee_vehiculo] [bit] NOT NULL,
	[identificacion_cliente] [varchar](25) NOT NULL,
	[id_habitacion] [int] NOT NULL,
 CONSTRAINT [PK_RESERVACION] PRIMARY KEY CLUSTERED 
(
	[id_reservacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RESERVACION]  WITH CHECK ADD  CONSTRAINT [FK_RESERVACION_CLIENTE] FOREIGN KEY([identificacion_cliente])
REFERENCES [dbo].[CLIENTE] ([identificacion])
GO

ALTER TABLE [dbo].[RESERVACION] CHECK CONSTRAINT [FK_RESERVACION_CLIENTE]
GO

ALTER TABLE [dbo].[RESERVACION]  WITH CHECK ADD  CONSTRAINT [FK_RESERVACION_HABITACION] FOREIGN KEY([id_habitacion])
REFERENCES [dbo].[HABITACION] ([id_habitacion])
GO

ALTER TABLE [dbo].[RESERVACION] CHECK CONSTRAINT [FK_RESERVACION_HABITACION]
GO

ALTER TABLE [dbo].[RESERVACION]  WITH CHECK ADD  CONSTRAINT [CK_RESERVACION_CANT] CHECK  (([cantidad_personas]>=(1)))
GO

ALTER TABLE [dbo].[RESERVACION] CHECK CONSTRAINT [CK_RESERVACION_CANT]
GO

ALTER TABLE [dbo].[RESERVACION]  WITH CHECK ADD  CONSTRAINT [CK_RESERVACION_FECHAS] CHECK  (([fecha_salida]>[fecha_hora_ingreso]))
GO

ALTER TABLE [dbo].[RESERVACION] CHECK CONSTRAINT [CK_RESERVACION_FECHAS]
GO

USE [ProyectoHotel]
GO

/****** Object:  Table [dbo].[FACTURA]    Script Date: 7/1/2026 20:34:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTURA](
	[id_factura] [int] IDENTITY(1,1) NOT NULL,
	[fecha_hora_registro] [datetime2](0) NOT NULL,
	[noches] [int] NOT NULL,
	[cargos_habitacion] [decimal](12, 2) NOT NULL,
	[importe_total] [decimal](12, 2) NOT NULL,
	[metodo_pago] [nvarchar](20) NOT NULL,
	[id_reservacion] [int] NOT NULL,
 CONSTRAINT [PK_FACTURA] PRIMARY KEY CLUSTERED 
(
	[id_factura] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_FACTURA_RESERVACION] UNIQUE NONCLUSTERED 
(
	[id_reservacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [FK_FACTURA_RESERVACION] FOREIGN KEY([id_reservacion])
REFERENCES [dbo].[RESERVACION] ([id_reservacion])
GO

ALTER TABLE [dbo].[FACTURA] CHECK CONSTRAINT [FK_FACTURA_RESERVACION]
GO

ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [CK_FACTURA_METODO] CHECK  (([metodo_pago]='Tarjeta' OR [metodo_pago]='Efectivo'))
GO

ALTER TABLE [dbo].[FACTURA] CHECK CONSTRAINT [CK_FACTURA_METODO]
GO

ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [CK_FACTURA_MONTOS] CHECK  (([cargos_habitacion]>=(0) AND [importe_total]>=(0)))
GO

ALTER TABLE [dbo].[FACTURA] CHECK CONSTRAINT [CK_FACTURA_MONTOS]
GO

ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [CK_FACTURA_NOCHES] CHECK  (([noches]>=(1)))
GO

ALTER TABLE [dbo].[FACTURA] CHECK CONSTRAINT [CK_FACTURA_NOCHES]
GO



